# Generated by Django 2.2.4 on 2021-03-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rei_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='postal_code',
            field=models.IntegerField(),
        ),
    ]
