# Generated by Django 2.2.4 on 2021-03-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('rei_app', '0002_auto_20210301_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='investors',
            field=models.ManyToManyField(related_name='leads', to='login_app.User'),
        ),
    ]
