# Generated by Django 2.2.4 on 2021-03-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rei_app', '0003_lead_investors'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='listing',
            field=models.TextField(null=True),
        ),
    ]
